apiVersion: v1
description: A Helm chart for fulfillment
home: https://github.com/giantswarm/fulfillment
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
name: fulfillment
version: 0.0.5
annotations:
  application.giantswarm.io/team: "planeteers"
